#!/usr/bin/env python3
"""
Run ABC-SMC inference for a tumour using its bulk methylation array as the
initial methylation state for all simulations.

Instead of starting every simulation from a random 50/50 binary array, this
uses the pre-processed avg(bulk_A, bulk_B) array so all proposals begin from
the same empirical initial state. This removes initial-condition stochasticity
and makes the ABC distance focus on divergence dynamics.

Requires the modified methdemon binary that accepts a file path for the
manual_array config parameter (not just -1 or a float).

Pre-processed init arrays live in data/bulk_init_arrays/tumour_{ID}_init.txt
(generated by prepare_bulk_init_arrays.py).

Usage (from methabc root):
    # With Redis workers (HPC):
    python scripts/run_tumour_bulk_init.py -d J

    # Local multicore:
    python scripts/run_tumour_bulk_init.py -d J --local --cores 20

    # All tumours sequentially:
    for t in D E F I J M P S U X; do
        python scripts/run_tumour_bulk_init.py -d $t --local --cores 20
    done

Notes:
    - Tumour M's bulk arrays are poorly correlated with gland averages
      (r ~ 0). Results for M should be interpreted with caution.
    - Uses fCpG_loci_per_cell=1164 (matching the data) instead of 1200.
    - The init array has 2*1164 = 2328 binary values.
"""

import os
import sys
import json
import tempfile
import subprocess
from pathlib import Path
from argparse import ArgumentParser

import numpy as np
import pandas as pd
import pyabc

# ── Paths ───────────────────────────────────────────────────────────

METHABC_ROOT = Path(__file__).resolve().parent.parent
MODEL_PATH = METHABC_ROOT / "resources" / "methdemon" / "bin" / "methdemon"
CONFIG_TEMPLATE = METHABC_ROOT / "resources" / "config_template.dat"
DATA_DIR = METHABC_ROOT / "data"
INIT_ARRAYS_DIR = DATA_DIR / "bulk_init_arrays"
MANIFEST_PATH = INIT_ARRAYS_DIR / "manifest.json"

TUMOUR_IDS = ["D", "E", "F", "I", "J", "M", "P", "S", "U", "X"]
N_LOCI = 1164  # fCpG loci in the filtered data


# ── Config writing ──────────────────────────────────────────────────

def read_template():
    with open(CONFIG_TEMPLATE, 'r') as f:
        return f.readlines()


def write_config(params, output_dir, init_array_path, template_lines):
    """Write config with manual_array pointing to the init file."""
    seed = np.random.randint(1, 2**15 - 1)

    full_params = dict(params)
    full_params['seed'] = seed
    full_params['left_demes'] = 4
    full_params['right_demes'] = 4
    full_params['fCpG_loci_per_cell'] = N_LOCI

    updated = []
    for line in template_lines:
        parts = line.split(maxsplit=1)
        if parts and parts[0] == 'manual_array':
            updated.append(f"    manual_array {init_array_path}\n")
        elif parts and parts[0] in full_params:
            val = full_params[parts[0]]
            if isinstance(val, (int, np.integer)):
                updated.append(f"    {parts[0]} {val}\n")
            elif isinstance(val, float):
                updated.append(f"    {parts[0]} {val:.10f}\n")
            else:
                updated.append(f"    {parts[0]} {val}\n")
        else:
            updated.append(line)

    config_path = os.path.join(output_dir, 'config.dat')
    with open(config_path, 'w') as f:
        f.writelines(updated)
    return config_path


# ── Simulation ──────────────────────────────────────────────────────

# These globals are set in main() / worker init
_TEMPLATE_LINES = None
_INIT_ARRAY_PATH = None


def simulate(params):
    """Run a single methdemon simulation with fixed init array."""
    tmpdir = tempfile.mkdtemp(prefix='bulkinit_')
    try:
        config_path = write_config(
            params, tmpdir, _INIT_ARRAY_PATH, _TEMPLATE_LINES)

        result = subprocess.run(
            [str(MODEL_PATH), tmpdir, 'config.dat'],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            timeout=300,
        )
        if result.returncode != 0:
            return None

        data_path = os.path.join(tmpdir, 'final_demes.csv')
        if not os.path.exists(data_path):
            return None

        df = pd.read_csv(data_path, header=0)
        df.AverageArray = df.AverageArray.apply(
            lambda x: np.fromstring(x, sep=";"))
        df = df[np.floor(df.Generation) == np.floor(df.Generation.max())]
        df = df.reset_index(drop=True)
        if df.shape[0] > 8:
            df = df.iloc[:8]
        return df

    except Exception:
        return None
    finally:
        import shutil
        shutil.rmtree(tmpdir, ignore_errors=True)


def log_model_abc_bulk(log_params):
    """ABC wrapper: log10 params -> natural scale -> simulate with fixed init."""
    params = {k: 10**v for k, v in log_params.items()
              if k != "s_driver_birth"}
    params["s_driver_birth"] = log_params["s_driver_birth"]
    res = simulate(params)
    return {"data": res}


# ── Distance (reuse methabc's CombinedDistance) ─────────────────────

def _get_distance():
    """Import the CombinedDistance from methabc."""
    try:
        from methabc.distance import CombinedDistance
        return CombinedDistance()
    except ImportError:
        # Fallback: add src to path
        sys.path.insert(0, str(METHABC_ROOT / "src"))
        from methabc.distance import CombinedDistance
        return CombinedDistance()


# ── Data import ─────────────────────────────────────────────────────

def import_data(data_path):
    """Import tumour data, same as methabc.utils.import_data."""
    data = pd.read_csv(data_path, index_col=0).dropna()
    columns_a = sorted([col for col in data.columns if "A" in col], key=len)
    columns_b = sorted([col for col in data.columns if "B" in col], key=len)
    other = [col for col in data.columns
             if "A" not in col and "B" not in col]
    data = data[columns_a + columns_b + other]
    return data


# ── Worker init for multiprocessing ─────────────────────────────────

def _init_worker(template_lines, init_path):
    global _TEMPLATE_LINES, _INIT_ARRAY_PATH
    _TEMPLATE_LINES = template_lines
    _INIT_ARRAY_PATH = init_path


# ── Main ────────────────────────────────────────────────────────────

def main():
    global _TEMPLATE_LINES, _INIT_ARRAY_PATH

    parser = ArgumentParser(
        description='ABC-SMC inference with bulk-array initial condition')
    parser.add_argument('-d', '--data_id', type=str, required=True,
                        help='Tumour ID (e.g. J, M, D)')
    parser.add_argument('--local', action='store_true',
                        help='Use local multicore instead of Redis')
    parser.add_argument('--cores', type=int, default=20,
                        help='Cores for local mode (default: 20)')
    parser.add_argument('--pop_size', type=int, default=1000,
                        help='ABC population size (default: 1000)')
    parser.add_argument('--max_gen', type=int, default=25,
                        help='Max ABC-SMC generations (default: 25)')
    parser.add_argument('--redis_host', type=str, default='127.0.0.1')
    parser.add_argument('--redis_port', type=int, default=2166)
    parser.add_argument('--db_dir', type=str, default='tmp',
                        help='Directory for output databases')
    args = parser.parse_args()

    data_id = args.data_id
    if data_id not in TUMOUR_IDS:
        print(f"ERROR: Unknown tumour ID '{data_id}'. "
              f"Must be one of: {TUMOUR_IDS}")
        sys.exit(1)

    # Check init array exists
    init_path = INIT_ARRAYS_DIR / f"tumour_{data_id}_init.txt"
    if not init_path.exists():
        print(f"ERROR: Init array not found: {init_path}")
        print("Run scripts/prepare_bulk_init_arrays.py first.")
        sys.exit(1)
    _INIT_ARRAY_PATH = str(init_path)

    # Check manifest for warnings
    if MANIFEST_PATH.exists():
        with open(MANIFEST_PATH) as f:
            manifest = json.load(f)
        info = manifest.get(data_id, {})
        if info.get('flag'):
            print(f"*** WARNING for tumour {data_id}: {info['flag']} ***")
            print(f"    r(bulk, gland_avg) = "
                  f"{info.get('r_bulk_vs_gland_avg', '?'):.3f}")
            print()

    # Check binary
    if not MODEL_PATH.exists():
        print(f"ERROR: methdemon binary not found at {MODEL_PATH}")
        print("Compile with: cd resources/methdemon && make")
        sys.exit(1)

    # Load template and data
    _TEMPLATE_LINES = read_template()

    data_path = DATA_DIR / "individual" / f"tumour_{data_id}.csv"
    if not data_path.exists():
        print(f"ERROR: Data file not found: {data_path}")
        sys.exit(1)

    observation = import_data(str(data_path))
    print(f"Tumour {data_id}: {len(observation)} loci, "
          f"{len(observation.columns)} glands")
    print(f"Init array: {_INIT_ARRAY_PATH}")

    # Priors (same as log_model.py)
    unif_params = {
        'meth_rate': (-4, -2),
        'demeth_rate': (-4, -2),
        'init_migration_rate': (-3.3, -1),
        'mu_driver_birth': (-5, -2),
        's_driver_birth': (0, .2),
    }

    prior = pyabc.Distribution(
        **{key: pyabc.RV("uniform", a, b - a)
           for key, (a, b) in unif_params.items()})

    # Distance
    distance = _get_distance()

    # Sampler
    if args.local:
        from pyabc.sampler import MulticoreEvalParallelSampler
        sampler = MulticoreEvalParallelSampler(n_procs=args.cores)
        print(f"Using local multicore sampler ({args.cores} cores)")
    else:
        from pyabc.sampler import RedisEvalParallelSampler
        sampler = RedisEvalParallelSampler(
            host=args.redis_host, port=args.redis_port)
        print(f"Using Redis sampler ({args.redis_host}:{args.redis_port})")

    # ABC
    abc = pyabc.ABCSMC(
        log_model_abc_bulk,
        prior,
        distance,
        population_size=args.pop_size,
        sampler=sampler,
    )

    db_dir = Path(args.db_dir)
    db_dir.mkdir(parents=True, exist_ok=True)
    db_path = db_dir / f"bulk_init_{data_id}.db"

    abc.new(
        db="sqlite:///" + str(db_path),
        observed_sum_stat={"data": observation},
    )

    print(f"\nStarting inference: pop={args.pop_size}, "
          f"max_gen={args.max_gen}")
    print(f"Database: {db_path}")

    history = abc.run(
        max_nr_populations=args.max_gen,
        minimum_epsilon=0,
        min_acceptance_rate=0.03,
    )

    print(f"\nDone. Final generation: {history.max_t}")
    print(f"Database: {db_path}")


if __name__ == "__main__":
    main()
